config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :category, only: [:show]
  resources :tweets, only: [:new,:create]
  resources :posts, only: [:index, :new, :create,:show,:destroy] do
    resources :comments, only: :create
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  # accepts_nested_attributes_for :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, :presence => true
  belongs_to :post  
  belongs_to :user  
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :video, VideoUploader
  has_many :comments
  # belongs_to :category
  # accepts_nested_attributes_for :category
  validates :text,:video, :presence => true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text,:date, :presence => true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments  
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :name, :email, :password, :password_confirmation　]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

  # def show
  #   @posts = Post.find(params[:category_id])
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @comment=Comment.create(comment_params)
    redirect_to post_path(@comment.post_id)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user
  def index
    @tweets = Tweet.all.order(updated_at: :desc).limit(1)
    @category = Category.all
    @post = Post.all.order(updated_at: :desc).limit(1)
    @posts = Post.all 


    
  end

  def new
   
    @post = Post.new
    # @post.build_category

  end

  def create

    @post = Post.create(post_params)
    # @post.save
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end
  

  private

  def post_params
    params.require(:post).permit(:text, :video)

  end

  # def post_params
  #   params.require(:post).permit(:text, :video,category_attributes:[:text,:post_id])

  # end


  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to new_user_session_path
    end
end


def logged_in?
  !current_user.nil?
end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :logged_in_user
  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
    redirect_to root_path
  end




  private

  def tweet_params
    params.require(:tweet).permit(:date,:place,:text)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to new_user_session_path
    end
end


def logged_in?
  !current_user.nil?
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AthleteNew
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/index.html.haml
= render "template/template_header"

.post__index__main
  .post__index__main__center
    .post__index__main__center__content
      .post__index__main__center__content__title
        %p 最新の投稿
        - @post.each do |post|
          = link_to "詳細" ,post_path("#{post.id}")
      - @post.each do |post|
        %video{:class=>"post__index__main__center__content__video",:autoplay => "", :loop => "", :muted => "", :src => "#{post.video}"}
    .post__index__main__center__yotei
      .post__index__main__center__yotei__content
        .post__index__main__center__yotei__content__title
          %p 明日の予定
        - @tweets.each do |tweet|
          .post__index__main__center__yotei__content__text
            %p 日時: #{tweet.date}
            %br/
            %p 場所: #{tweet.place}
            %br/
            %p 本文: #{tweet.text}
            %br/
    .post__index__main__center__tweet
      %a.twitter-timeline{:href => "https://twitter.com/Triumphant_Lion?ref_src=twsrc%5Etfw"} Tweets by Triumphant_Lion
      %script{:async => "", :charset => "utf-8", :src => "https://platform.twitter.com/widgets.js"}






  .post__index__main__right
    - @posts.each do |post1|
      .post__index__main__right__content__text
        .post__index__main__right__content__text__text
          =link_to "#{post1.text}",post_path("#{post1.id}"),class:"ooo"
        %video{:class=>"post__index__main__right__content__video",:autoplay => "", :loop => "", :muted => "", :src => "#{post1.video}"}
        
        
      
= render "template/template_footer"

app/views/posts/new.html.haml
= render "template/template_header"
.post__new
  .post__new__center
    .post__new__center__title
      %h1 動画投稿
    .post__new__center__content
      .post__new__center__content__main
        = form_for(@post) do |f|
          %p タイトル ※必須項目
          =f.text_field :text, placeholder: :タイトルを入力してください, class: :post__new__center__content__main__title
          %br/
          
          = f.file_field :video, placeholder: "Video Url" ,class: :post__new__center__content__main__video
          %br/
          -# = f.fields_for :category do |i|
          -#   =i.text_field :text 
          = f.submit "投稿する" 

= render "template/template_footer"

app/views/posts/show.html.haml
= render "template/template_header"

.post__show
  .post__show__left
    .post__show__left__content
      .post__show__left__content__title
        %p  #{@post.text}
        -# = link_to "削除","posts/post.id"
        = link_to '削除', "/posts/#{@post.id}",method: :delete

      %video{:class=>"post__show__left__content__video",:autoplay => "", :loop => "", :muted => "", :src => "#{@post.video}"}

  .post__show__right
    .post__show__right__coment
      - if @comments
        - @comments.each do |comment|
          .coment__list
            = comment.user.name
            = comment.text

    .post__show__right__form
      = form_with(model: [@post, @comment], class: :form, local: true) do |form|
        = form.text_field :text, placeholder: :コメント, class: :form__title
        = form.submit "投稿", class: :btn


= render "template/template_footer"

app/views/template/_template_footer.html.haml
.main__footer
  = link_to "HOME",root_path
  = link_to "NEW VIDEOS",new_post_path()
  = link_to "NEW SCHEDULE", new_tweet_path()
  = link_to "LOG OUT",destroy_user_session_path(),method: :delete 
  = link_to "TWITTER",'https://twitter.com/Triumphant_Lion?ref_src=twsrc%5Etfw%7Ctwcamp%5Eembeddedtimeline%7Ctwterm%5Eprofile%3ATriumphant_Lion&ref_url=http%3A%2F%2Flocalhost%3A3000%2F'
 

app/views/template/_template_header.html.haml
.main__header
  .main__header__title
    = link_to "Athlete",root_path
  .main__header__login
    -# = link_to "新規会員登録", new_user_registration_path()
    -# = link_to "ログイン", new_user_session_path()
    = link_to "動画の投稿", new_post_path()
    = link_to "予定の追加", new_tweet_path()

app/views/tweets/new.html.haml
= render "template/template_header"
.tweet__main
  .tweet__main__content
    .tweet__main__content__title
      %p 明日の予定
    .tweet__main__content__text
      = form_with model: @tweet, class: :form, local: true do |form|
        %span 予定日 
        %br/
        = form.text_field :date, placeholder: :"例2020/11/22", class: :tweet__main__content__text__form
        %span 集合 
        %br/
        = form.text_field :place,  placeholder: :○○駅, class: :tweet__main__content__text__form
        %span 内容
        %br/
        = form.text_area :text, placeholder: :内容, class: :tweet__main__content__text__low
        %br/
        = form.submit "投稿する", class: :tweet__main__content__text__submit
= render "template/template_footer"